# Generated by Django 3.1.4 on 2021-01-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='mypost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('myfile', models.FileField(upload_to='upload')),
                ('comment', models.TextField()),
            ],
        ),
    ]
